// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char Thing_ID[] = "5c8142b8-6c6c-4b0e-a158-c2e95be56074";
const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAlarmMessageChange();
void onHumidityChange();
void onTemperatureChange();
void onAlarmStatusChange();

String alarm_message;
float humidity;
float temperature;
bool alarm_status;

void initProperties(){

  ArduinoCloud.addProperty(alarm_message, READWRITE, ON_CHANGE, onAlarmMessageChange);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(alarm_status, READWRITE, ON_CHANGE, onAlarmStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
